### ISSUE TITLE
一些关于论文的疑问。

### ISSUE THREAD

**Issue by faicaiwawa** [LiYunfengLYF/UOSTrack#2]
非常感谢您的开源，目前有关水下跟踪的研究很少，这篇文章给了我很多启发。关于论文我有一些疑问：

**- 关于OStack预训练模型的版本**
    我根据在论文第5.8节“The template size is set to 128×128 and the search area size is set to 256×256. ” 我猜测您使用的是256版本的OSTrack。但当我使用OSTrack256预训练模型在UTB180测试，使用自带的"analysis_results.py"进行评估时，AUC结果只有61+，我又用了384版本进行测试,AUC结果为62+，两个模型都达不到您在Comparision中的63+。

**- 关于UOSTrack的推理速度**
    第5.8节“The statistical results show that our proposed UOSTrack could run at a rapid rate of 110 FPS.” ，我使用小体积的OSTrack256版本在不使用您的KF模块的情况下使用3060GPU进行推理，只有大概70FPS。您是如何在算力受限的边缘设备 NVIDIA Jetson AGX Xavier 上运行到110FPS的？ TensorRT+量化吗？

**- 关于UOSTrack的训练细节**
 我在阅读时没有看到很细致的训练策略，请问您是不使用OSTrack的预训练权重， 从零开始训练OSTrack+KF模块吗？

**Comment by LiYunfengLYF** [comment]
@faicaiwawa 关于第一个问题，OSTrack自身的性能在3090Ti，win10系统上是能达到63.03%的，如果性能达不到的话，试试换换不同的显卡，还有不同的操作系统。关于第二个问题，对的，我们进行了部署的操作。关于第三个问题，我们在训练阶段，没有使用OSTrack已有的模型作为预训练权重，而是只使用了MAE模型作为预训练权重，KF模块只在测试时候使用了。

**Comment by faicaiwawa** [comment]
> @faicaiwawa 关于第一个问题，OSTrack自身的性能在3090Ti，win10系统上是能达到63.03%的，如果性能达不到的话，试试换换不同的显卡，还有不同的操作系统。关于第二个问题，对的，我们进行了部署的操作。关于第三个问题，我们在训练阶段，没有使用OSTrack已有的模型作为预训练权重，而是只使用了MAE模型作为预训练权重，KF模块只在测试时候使用了。

好的谢谢
